const users = [
    {
        id: 2,
        email: 'davidbowie@gmail.com',
        name: 'David Bowie',
        username: 'ziggystardust7', 
        password: 'Heroes31', 
        instrument: [5, 6], 
        city: 2, 
        instagram: '@davidbowieofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/davidbowie', 
        bandcamp: 'www.bandcamp.com/davidbowie', 
        spotify: '', 
        bio: 'Singer/songwriter hailing from London, also known as Major Tom, the Think White Duke, etc.', 
        img: ''
    }, 
    {
        id: 3,
        email: 'steviewonder@gmail.com',
        name: 'Stevie Wonder',
        username: 'higherground11', 
        password: 'superstition55', 
        instrument: [4, 5, 6], 
        city: 1, 
        instagram: '@steviewonderofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/steviewonder', 
        bandcamp: 'www.bandcamp.com/steviewonder', 
        spotify: 'https://open.spotify.com/artist/7guDJrEfX3qb6FEbdPA5qi?si=9VIJiMZIQkOp-aA07RWQ9Q', 
        bio: 'I might not be able to see but I am FUNKY.', 
        img: ''
    }, 
    {
        id: 4,
        email: 'stevienicks@gmail.com',
        name: 'Stevie Nicks',
        username: 'Rhiannon81', 
        password: 'egdeof17', 
        instrument: [5], 
        city: 1, 
        instagram: '@stevienicksofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/stevienicks', 
        bandcamp: 'www.bandcamp.com/stevienicks', 
        spotify: '', 
        bio: 'I\'m not a witch, I swear.', 
        img: ''
    }, 
    {
        id: 5,
        email: 'dave_grohl@gmail.com',
        name: 'Dave Grohl',
        username: 'thepretender', 
        password: 'Marigold1', 
        instrument: [1, 3, 5], 
        city: 1, 
        instagram: '@davegrohlofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/foofighters', 
        bandcamp: 'www.bandcamp.com/foofighters', 
        spotify: '', 
        bio: 'Drummer who can only play loud.', 
        img:''
    }, 
    {
        id: 6,
        email: 'slash@gmail.com',
        name: 'Slash',
        username: 'mrbrownstone2', 
        password: 'paradisecity3', 
        instrument: [1], 
        city: 1, 
        instagram: '@slashofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/gunsnroses', 
        bandcamp: 'www.bandcamp.com/gunsnroses', 
        spotify: '', 
        bio: 'Seeking a vocalist named Axl.', 
        img:''
    }, 
    {
        id: 7,
        email: 'flea@gmail.com',
        name: 'Flea',
        username: 'californication9', 
        password: 'underthebridge7', 
        instrument: [2], 
        city: 1, 
        instagram: '@fleaofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/redhotchilipeppers', 
        bandcamp: 'www.bandcamp.com/redhotchilipeppers', 
        spotify: '', 
        bio: 'giveitawaygiveitawaygiveitawaynow.', 
        img:''
    }, 
    {
        id: 8,
        email: 'herbiehancock@gmail.com',
        name: 'Herbie Hancock',
        username: 'Chameleon65', 
        password: 'headhunters88', 
        instrument: [4], 
        city: 1, 
        instagram: '@herbiehancockofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/herbiehancock', 
        bandcamp: 'www.bandcamp.com/herbiehancock', 
        spotify: '', 
        bio: 'giveitawaygiveitawaygiveitawaynow.', 
        img:''
    }, 
    {
        id: 9,
        email: 'quincyjones@gmail.com',
        name: 'Quincy Jones',
        username: 'offthewall32', 
        password: 'beatit543', 
        instrument: [6], 
        city: 1, 
        instagram: '@quincyjonesofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/quincyjones', 
        bandcamp: 'www.bandcamp.com/quincyjones', 
        spotify: '', 
        bio: 'You can\'t save a bad song', 
        img:''
    }, 
    {
        id: 10,
        email: 'debbieharry@gmail.com',
        name: 'Debbie Harry',
        username: 'heartofglass22', 
        password: 'callme41', 
        instrument: [5], 
        city: 2, 
        instagram: '@Debbieharryofficial', 
        facebook: '', 
        twitter: '', 
        soundcloud: 'www.soundcloud.com/blondie', 
        bandcamp: 'www.bandcamp.com/blondie', 
        spotify: '', 
        bio: 'One way or another, I\'m gonna get ya', 
        img:''
    }
]

export default users